name: http_pref_example
description: Demonstrates how to use the http_pref plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http_pref:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true