name: http_pref
description: Making your app offline ready. Uses http for network requests and sharedprefences for cache
version: 0.0.2
homepage: https://github.com/naxa-developers/http_pref

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4


dev_dependencies:
  flutter_test:
    sdk: flutter


